# MOVIE DATA ANALYSIS PROJECT IN R
# Dataset: movies_genre_dataset_cleaned.xlsx
# Covers: Fundamentals, Wrangling, Visualization, Analysis

# --- Load Required Libraries ---
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)

# Import Dataset
# movies <- read_csv("SDAUR/FA-2/cleaned_data.csv")
library(readr)
movies <- read_csv("C:/Users/Rajkumar Dewke/__Coding_with_SaranG__/R/Movie_Rating_Prediction_Project/cleaned_data.csv")
#View(cleaned_data)

# Explore structure and summary
head(movies)
tail(movies)
summary(movies)
colnames(movies)
colSums(is.na(movies)) # Missing value - summary


# Handling missing values:
movies$director[is.na(movies$director)] <- "Unknown"
movies$cast[is.na(movies$cast)] <- "Unknown"
movies <- movies %>% drop_na(genres)

# Profit:
movies <- mutate(movies, profit = revenue - budget)


# 1
## Relationship Between Duration & Rating:
ggplot(movies, aes(x = runtime, y = vote_average)) + geom_point(alpha = 0.6, color = "steelblue") + geom_smooth(method = "lm", se = TRUE, color = "darkred") +
  labs(title = "Relationship Between Movie Duration and User Rating Average", x = "Movie Duration (Minutes)", y = "User Rating") + 
  theme_minimal()
# “The analysis shows a weak positive correlation between movie runtime and
# user ratings — longer movies tend to receive slightly higher ratings, though
# the relationship is not very strong.”

# &

# Average Runtime by Genre:
avg_runtime_genre <- movies %>%
  group_by(genres) %>%
  summarise(
    avg_runtime = mean(runtime, na.rm = TRUE),
    avg_rating = mean(vote_count, na.rm = TRUE),
    count = n()
  ) %>%
  arrange(desc(avg_runtime))
View(avg_runtime_genre)

print(avg_runtime_genre)
# Conclusion:
# Adventure, Action, Fantasy, and Science Fiction movies generally get the highest ratings,
# while Western, Foreign, and Documentary genres receive lower ratings. Drama and Thriller are
# made in the highest numbers, but their ratings are average.
# In summary: highly rated genres are less common, and the most common genres tend
# to have moderate ratings.


# 2
## Visualization
# Average Runtime vs Average Rating (by Genre):
ggplot(avg_runtime_genre, aes(x = avg_runtime, y = avg_rating, label = genres)) +
  geom_point(color = "darkorange", size = 3) +
  geom_text(vjust = -1, size = 5) +
  labs(
    title = "Average Runtime vs Average Rating (by Genre)",
    x = "Average Runtime (minutes)",
    y = "Average Rating"
  ) +
  theme_minimal()
# Conclusion:
# The graph means that movie type (genre) matters more for ratings than how long the movie is.
# For example, some short movies can get high ratings, and some long movies do not always get
# the best ratings.



# 3
#### Return of Investment:
## Which movies achieved the highest return on investment (ROI = revenue / budget)?
movies <- movies %>% mutate(ROI = ifelse(budget > 0, revenue / budget, NA))
top_popular_roi <- movies %>% filter(!is.na(popularity)) %>% arrange(desc(popularity)) %>% distinct(original_title, .keep_all = TRUE) %>% select(original_title, budget, revenue, ROI, popularity)
print(top_popular_roi)

top20 <- top_popular_roi %>% head(20)

# Plot: Popularity vs ROI
ggplot(top10, aes(x = reorder(original_title, ROI), y = ROI, fill = popularity)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top 20 Most Popular Movies by ROI",
    x = "Movie Title",
    y = "Return on Investment (ROI)",
    fill = "Popularity"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12)
  )

# 4
## Analyze the correlation between budget and revenue. Do higher-budget movies always generate more revenue?
# Correlation Between Budget and Revenue
ggplot(movies, aes(x = budget, y = revenue)) + geom_point(alpha = 0.5, color = "mediumseagreen") +
  geom_smooth(method = "lm", se = TRUE, color = "darkred") +
  labs(title = "Correlation: Movie Budget vs Revenue", x = "Budget", y = "Revenue") +
  theme_minimal()

correlation <- cor(movies$budget, movies$revenue, use = "complete.obs")
cat("Correlation between budget and revenue: ", correlation, "\n")
# The Scatter plot and correlation coefficient tell if bigger budgets
# consistently get more revenue.

# 5
## Identify the top 5 production companies in terms of total revenue generated by their movies.
# Top 5 Production Companies by Total Revenue
top_companies <- movies %>%
  filter(!is.na(production_companies)) %>%
  group_by(production_companies) %>%
  summarise(total_revenue = sum(revenue, na.rm = TRUE),
            num_movies = n()) %>%
  arrange(desc(total_revenue)) %>%
  head(5)

top_companies$production_companies_wrapped <- str_wrap(top_companies$production_companies, width = 15)

ggplot(top_companies, aes(x = reorder(production_companies_wrapped, -total_revenue), y = total_revenue, fill = num_movies)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = num_movies), vjust = -0.5, size = 3.5) +
  labs(
    title = "Total Revenue by Production Company",
    x = "Production Company",
    y = "Total Revenue",
    fill = "Number of Movies"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
# Conclusion:
# The top 5 production companies generate the highest total movie revenue, making
# them the most financially successful and prolific producers in the dataset.


# 6
# Identify outliers: movies with very high ratings but low votes, and
# vice versa.
high_popularity_threshold <- 80 # example, adjust based on your data
low_vote_threshold <- 100
high_pop_low_votes <- subset(movies,popularity >= high_popularity_threshold & vote_count < low_vote_threshold)

print("High Popularity but Low Votes:")
print(high_pop_low_votes[, c("original_title", "popularity", "vote_count")])

low_popularity_threshold <- 20 # example, adjust based on your data
high_vote_threshold <- 10000
low_pop_high_votes <- subset(movies, popularity <= low_popularity_threshold & vote_count > high_vote_threshold)

print("Low Popularity but High Votes:")
print(low_pop_high_votes[, c("original_title", "popularity", "vote_count")])

ggplot(movies, aes(x = vote_count, y = popularity)) + geom_point(alpha = 0.4) +
  geom_point(data = high_pop_low_votes, aes(x = vote_count, y = popularity), color = "green", size = 3) +
  geom_point(data = low_pop_high_votes, aes(x = vote_count, y = popularity), color = "red", size = 3) +
  scale_x_log10() + labs(title = "Outliers in Votes vs Popularity", x = "Number of Votes (log scale)", y = "Popularity") +
  theme_minimal()
# For popularity
Q1_pop <- quantile(movies$popularity, 0.25)
Q3_pop <- quantile(movies$popularity, 0.75)
IQR_pop <- Q3_pop - Q1_pop
# For vote count
Q1_vote <- quantile(movies$vote_count, 0.25)
Q3_vote <- quantile(movies$vote_count, 0.75)
IQR_vote <- Q3_vote - Q1_vote
# Outliers: values beyond 1.5 * IQR
outliers <- subset(movies,
                    popularity < (Q1_pop - 1.5 * IQR_pop) |
                    popularity > (Q3_pop + 1.5 * IQR_pop) |
                    vote_count < (Q1_vote - 1.5 * IQR_vote) |
                    vote_count > (Q3_vote + 1.5 * IQR_vote))
# Conclusion:
# Most movies have low popularity and low vote counts, clustering in the lower-left of the plot
# Outliers with very high popularity but low votes suggest new, hyped, or niche films.
# Outliers with low popularity but high votes point to widely watched but poorly-rated or older movies.
# Statistically significant outliers appear far from the dense cluster, breaking typical trends in audience preferences.


# 7
# Analyzing the trend of average movie ratings over the years.
sum(is.na(movies))
sum(duplicated(movies))
movies_per_year = movies %>% group_by(release_year) %>% summarise(total_movies =
                                                                          n())
ggplot(movies_per_year,aes(x=release_year,y =total_movies))+geom_line(color = 'blue')+
  geom_point(color='red')+theme_minimal()
# Conclusion:
# It is generally increased over time, and significant growth is observed from the 1990s onwards.
# Digital streaming platforms ( netfilx, amazon prime, disney+ ) have contributed to more release in recent years
# Minor dips in certain yearsn may be due to global events, but the long-term trend is upward.

# 8
# Average Revenue by Genre
avg_revenue <- aggregate(revenue ~ genres, data = movies, FUN = mean, na.rm = TRUE)
avg_revenue <- avg_revenue[order(-avg_revenue$revenue), ]
print(avg_revenue)
ggplot(avg_revenue, aes(x = reorder(genres, revenue), y = revenue, fill = genres)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(revenue,0)), hjust = -0.2, size = 3.5) +
  labs(title = "Average Revenue by Genre", x = "Revenue", y = "Genre") +
  theme_minimal() +
  coord_flip()
# Conclusion:
# Adventure, fantasy, family, and animation genres genreate the highest average revenues,
# indicating strong audience demand and broad appeal.

# 9
# Which genres are the most popular in terms of the number of movies released?
genre_count <- as.data.frame(table(movies$genres))
# Rename columns
colnames(genre_count) <- c("Genre", "Count")
# Sort descending
genre_count <- genre_count[order(-genre_count$Count), ]
# View result
print(genre_count)
ggplot(genre_count, aes(x = reorder(Genre, -Count), y = Count, fill = Genre)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Count), vjust = -0.3, size = 3.5) + # <-- Add counts on top
  labs(title = "Most Popular Movie Genres", x = "Genre", y = "Number of Movies") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
# Conclusion:
# Drama is the most popular genre, with highest no. of movies released and comedy, thriller, and action
# genres also have a large number of releases, indicating strong industry.

# 10
# Linear Regression:
# Relationship between movie budget and revenue using linear regression

#Step 1:Correlation Plot
numeric_data <- cleaned_data %>% select(where(is.numeric))
correlation_matrix <- cor(numeric_data, use = "complete.obs")
print(round(correlation_matrix, 2))
corrplot(correlation_matrix, method = "color", type = "full", tl.col = "black",
         tl.srt = 45, addCoef.col = "black", number.cex = 0.7,
         col = colorRampPalette(c("red", "white", "blue"))(200),
         title = "Correlation Heatmap")

#Step 2:ScatterPlot-Check linearity
ggplot(cleaned_data, aes(x = budget, y = revenue)) +
  geom_point(color = "darkorange", alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "steelblue", linewidth = 1) +
  labs(
    title = "Budget vs Revenue — Checking Linearity",
    x = "Budget (in millions)", y = "Revenue (in millions)"
  ) + theme_minimal()

#Step 3: Build linear model
# Linear regression model
model = lm(revenue ~ budget, data = cleaned_data)
# Model summary
summary(model)

#step 4: Visualize regression fit with prediction line
ggplot(cleaned_data, aes(x = budget, y = revenue)) +
  geom_point(alpha = 0.6, color = "gray40") +
  geom_smooth(method = "lm", color = "blue", se = TRUE) +
  labs(
    title = "Linear Regression: Revenue Predicted by Budget",
    x = "Budget", y = "Revenue"
  ) + theme_minimal()

# Conclusion:
# The linear regression analysis shows a significant positive relationship between movie budget and revenue.
# Financial performance is based on how the budget is strong
# Higher budgets genereally result in higher revenues

# 11
# Predictive Analysis:
# Load libraries
library(dplyr)
library(randomForest)
library(ggplot2)
# Select relevant columns from your dataset
movies <- movies %>%
  select(vote_average, budget, revenue, runtime, genres, vote_count, popularity) %>%
  na.omit()
# Convert genre to a factor (categorical)
movies$genres <- as.factor(movies$genres)
# Split data into training and testing sets (80/20)
set.seed(123)
train_index <- sample(1:nrow(movies), 0.8 * nrow(movies))
train_data <- movies[train_index, ]
test_data <- movies[-train_index, ]
# Random Forest Model
rf_model <- randomForest(vote_average ~ budget + revenue + runtime + genres +
                           vote_count + popularity, data = train_data, ntree = 500, mtry = 3,  importance = TRUE)
View(rf_model)
# Predictions & Evaluation
predictions <- predict(rf_model, test_data)
# Compute R-squared and RMSE
R2 <- 1 - sum((predictions - test_data$vote_average)^2) /
  sum((mean(test_data$vote_average) - test_data$vote_average)^2)
RMSE <- sqrt(mean((predictions - test_data$vote_average)^2))
cat("R-squared:", R2, "\n")
cat("RMSE:", RMSE, "\n")
# Feature Importance
importance(rf_model)
varImpPlot(rf_model, main = "Feature Importance in Predicting Vote Average")
# Actual vs Predicted Plot
ggplot(data = test_data, aes(x = vote_average, y = predictions)) +
  geom_point(alpha = 0.6, color = "steelblue") +
  geom_abline(linetype = "dashed", color = "red") +
  labs(title = "Actual vs Predicted Vote Averages (Random Forest)",
       x = "Actual Vote Average",
       y = "Predicted Vote Average") +
  theme_minimal()
# We have taken random samples!
#Testing
new_movie <- data.frame(
  budget = 120,
  revenue = 400,
  runtime = 130,
  genres = factor("Action", levels = levels(movies$genres)),
  vote_count = 2500,
  popularity = 60
)
predicted_rating <- predict(rf_model, new_movie)
predicted_rating
# Conclusion:
# The Random Forest model accurately predicted movie ratings using factors like
# budget, revenue, runtime, genres, vote count, and popularity. Popularity,
# vote count, and revenue were the most important factors.
# The model showed strong performance with good accuracy and reliability.
# It can be further improved by adding detailed genre or text features and fine-tuning parameters.

