# 🎬 MOVIE DATA ANALYSIS PROJECT IN R
# Dataset: movies_genre_dataset_cleaned.xlsx
# Covers: Fundamentals, Wrangling, Visualization, Analysis

# --- Load Required Libraries ---
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)

# Import Dataset
movies <- read_csv("SDAUR/FA-2/cleaned_data.csv")

# Explore structure and summary
head(movies)
tail(movies)
summary(movies)
colnames(movies)
colSums(is.na(movies)) # Missing value - summary


# Handling missing values:
movies$director[is.na(movies$director)] <- "Unknown"
movies$cast[is.na(movies$cast)] <- "Unknown"
movies <- movies %>% drop_na(genres)

# Profit:
movies <- mutate(movies, profit = revenue - budget)


# 1
## Relationship Between Duration & Rating:
ggplot(movies, aes(x = runtime, y = vote_average)) + geom_point(alpha = 0.6, color = "steelblue") + geom_smooth(method = "lm", se = TRUE, color = "darkred") +
  labs(title = "Relationship Between Movie Duration and User Rating Average", x = "Movie Duration (Minutes)", y = "User Rating") + 
  theme_minimal()
# “The analysis shows a weak positive correlation between movie runtime and
# user ratings — longer movies tend to receive slightly higher ratings, though
# the relationship is not very strong.”

# &

# Average Runtime by Genre:
avg_runtime_genre <- movies %>%
  group_by(genres) %>%
  summarise(
    avg_runtime = mean(runtime, na.rm = TRUE),
    avg_rating = mean(vote_count, na.rm = TRUE),
    count = n()
  ) %>%
  arrange(desc(avg_runtime))
View(avg_runtime_genre)

print(avg_runtime_genre)
# Conclusion:
# Adventure, Action, Fantasy, and Science Fiction movies generally get the highest ratings,
# while Western, Foreign, and Documentary genres receive lower ratings. Drama and Thriller are
# made in the highest numbers, but their ratings are average.
# In summary: highly rated genres are less common, and the most common genres tend
# to have moderate ratings.


# 2
## Visualization
# Average Runtime vs Average Rating (by Genre):
ggplot(avg_runtime_genre, aes(x = avg_runtime, y = avg_rating, label = genres)) +
  geom_point(color = "darkorange", size = 3) +
  geom_text(vjust = -1, size = 5) +
  labs(
    title = "Average Runtime vs Average Rating (by Genre)",
    x = "Average Runtime (minutes)",
    y = "Average Rating"
  ) +
  theme_minimal()
# Conclusion:
# The graph means that movie type (genre) matters more for ratings than how long the movie is.
# For example, some short movies can get high ratings, and some long movies do not always get
# the best ratings.



# 3
#### Return of Investment:
## Which movies achieved the highest return on investment (ROI = revenue / budget)?
movies <- movies %>% mutate(ROI = ifelse(budget > 0, revenue / budget, NA))
top_popular_roi <- movies %>% filter(!is.na(popularity)) %>% arrange(desc(popularity)) %>% distinct(original_title, .keep_all = TRUE) %>% select(original_title, budget, revenue, ROI, popularity)
print(top_popular_roi)

top20 <- top_popular_roi %>% head(20)

# Plot: Popularity vs ROI
ggplot(top10, aes(x = reorder(original_title, ROI), y = ROI, fill = popularity)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top 20 Most Popular Movies by ROI",
    x = "Movie Title",
    y = "Return on Investment (ROI)",
    fill = "Popularity"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12)
  )

# 4
## Analyze the correlation between budget and revenue. Do higher-budget movies always generate more revenue?
# Correlation Between Budget and Revenue
ggplot(movies, aes(x = budget, y = revenue)) + geom_point(alpha = 0.5, color = "mediumseagreen") +
  geom_smooth(method = "lm", se = TRUE, color = "darkred") +
  labs(title = "Correlation: Movie Budget vs Revenue", x = "Budget", y = "Revenue") +
  theme_minimal()

correlation <- cor(movies$budget, movies$revenue, use = "complete.obs")
cat("Correlation between budget and revenue: ", correlation, "\n")
# The Scatter plot and correlation coefficient tell if bigger budgets
# consistently get more revenue.

# 5
## Identify the top 5 production companies in terms of total revenue generated by their movies.
# Top 5 Production Companies by Total Revenue
top_companies <- movies %>%
  filter(!is.na(production_companies)) %>%
  group_by(production_companies) %>%
  summarise(total_revenue = sum(revenue, na.rm = TRUE),
            num_movies = n()) %>%
  arrange(desc(total_revenue)) %>%
  head(5)

top_companies$production_companies_wrapped <- str_wrap(top_companies$production_companies, width = 15)

ggplot(top_companies, aes(x = reorder(production_companies_wrapped, -total_revenue), y = total_revenue, fill = num_movies)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = num_movies), vjust = -0.5, size = 3.5) +
  labs(
    title = "Total Revenue by Production Company",
    x = "Production Company",
    y = "Total Revenue",
    fill = "Number of Movies"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
# Conclusion:
# The top 5 production companies generate the highest total movie revenue, making
# them the most financially successful and prolific producers in the dataset.



### 6  Multi-genre Movies:
# Do movies belonging to multiple genres tend to perform better
# (in revenue or rating) than single-genre movies?
movies_multi_genres <- movies %>% mutate(num_genres = lengths(strsplit(as.character(genres), ",")))

genre_state <- movies_multi_genres %>% group_by(num_genres) %>% summarise (
  avg_revenue = mean(revenue, na.rm = TRUE),
  avg_rating = mean(vote_average, na.rm = TRUE),
  movie_count = n()
) %>% arrange(num_genres)

# Boxplot for visual comparison
ggplot(movies_multi_genres, aes(x = as.factor(num_genres), y = vote_average)) +
  geom_boxplot(fill = "steelblue", outlier.colour = "red") +
  labs(title = "Distribution of Ratings by Number of Genres",
       x = "Number of Genres",
       y = "User Rating (vote_average)") +
  theme_minimal()

View(movies)


